version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0.3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/appointment-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/appoiment-api
    volumes:
      - ./dist/:/usr/src/appointment-api/dist/
      - ./package.json:/usr/src/appointment-api/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo